version: '3.8'

networks:
  db:
    impage: mysql:5.7
    container_name: conference
    ports:
      - 3306:3306
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: conference

